export { default as Avatar } from './components/Elements/Avatar/Avatar.vue'
export { default as AvatarGroup } from './components/Elements/Avatar/AvatarGroup.vue'
export { default as Badge } from './components/Elements/Badge/Badge.vue'
export { default as Button } from './components/Elements/Button/Button.vue'
export { default as ButtonGroup } from './components/Elements/Button/ButtonGroup.vue'
export { default as Card } from './components/Elements/Card/Card.vue'
export { default as Dropdown } from './components/Elements/Dropdown/Dropdown.vue'
export { default as Tooltip } from './components/Elements/Tooltip/Tooltip.vue'
export { default as Pagination } from './components/Elements/Pagination/Pagination.vue'
export { default as LoaderSpinner } from './components/Elements/Loader/LoaderSpinner.vue'
export { default as LoaderLinear } from './components/Elements/Loader/LoaderLinear.vue'
export { default as LoaderProgress } from './components/Elements/Loader/LoaderProgress.vue'

export { useVariantClasses, setVariantClasses } from './composables/variantClasses.ts'